### PR TITLE
React hooks

### PR DESCRIPTION
**Pull request by KwanMan**
Definitely not final but experimenting how the new react hooks could fit in with tiny-atom

```js
const createAtom = require('tiny-atom')
const { useAtom, useAtomState, useAtomAction } = require('tiny-atom/react')

const initialState = { name: 'tommy' }
function setName (atom, name) {
  atom.set({ name })
}
const atom = createAtom(initialState, { setName })

ReactDOM.render(
  <Provider atom={atom}>
    <Combined />
    <Separate />
  </Provider>,
  mountNode
)

function Combined () {
  const [name, setName] = useAtom(state => state.name, 'setName')
  return <input type='text' value={name} onChange={e => setName(e.target.value)} />
}

function Separate () {
  const name = useAtomState(state => state.name)
  const setName = useAtomAction('setName')
  return <input type='text' value={name} onChange={e => setName(e.target.value)} />
}
```

### CODE REVIEW

**Comment by KidkArolis** [comment]
👏 very nice

you _can_ use the old connect for function components, right? But this is meant to be cleaner syntax and less components in the tree and potentially more optimized (?) and more composable (?)

What about something like this:

```js
const { name, age } = useState(state => pick(state, 'name', 'age'))
const { setName, setAge } = useActions()
```

**Comment by KwanMan** [comment]
yea the old way will still work but this is meant to be more composable. it will definitely help with reducing the number of wrapper components in the tree but not sure about performance.

```js
const { name, age } = useState(state => pick(state, 'name', 'age'))
```

Since they have a `useState` hook, I think this will lead to a lot of name clashes. I'm with removing the `atom` reference in the fn name though, that's the way we've been going about it

```js
const { setName, setAge } = useActions()
```

Yea that's much cleaner, shouldn't need to type it twice every line. Means we'll need to bind every action on create (https://github.com/KidkArolis/tiny-atom/pull/63/files#diff-1fdf421c05c1140f6d71444ea2b27638R22) which should be alright. Although I feel liek there was something stopping us from doing this and exposing the actions as functions before 🤔 

tbh i'm very mixed with how hooks work. On one hand the concise syntax and having all the relevant logic for listeners together is super sweet but because it uses global state there's a lot of "magic" to it. 

Saying that, I've built a few things with it in the past few days and it's very intuitive.

**Comment by KidkArolis** [comment]
Started using this in a project. Really powerful, much easier to use than connecting. Will play with variants of API and see what feels best.

I think we could get away with just one function, something like:

```
const [{ user, toast }, { logout, setToast }] = useAtom(pick('user', 'toast'))
```

**Comment by KidkArolis** [comment]
Superseded by #66

**Pull request closed without merging**
