### PR TITLE
Experimental API #2 - tiny-atom/quarks

### PR DESCRIPTION
**Pull request by KidkArolis**
Ok, so this one's Alan's idea!

This might be a simpler and a more powerful abstraction compared to #32.

Check this yo:

```js
const createAtom = require('tiny-atom/quarks')
const merge = require('tiny-atom/deep-merge')
const debug = require('tiny-atom/log')

// signature is now (options, initialState = {})
const atom = = createAtom({ merge, debug })
```

First of all, you can add top level state and actions:

```js
atom({ a: 1 }, {
  plus: (get, split) => split({ a: get().a + 1 })
})
```

And extend the top level on demand:

```js
atom({ b: 1 }, {
  minus: (get, split) => { split({ b: get().b - 1 })
})
```

But you can also create scoped slices of atom - quarks

```js
const todo = atom('todo', { list: [], val: '' }, {
  add: (get, split, item, root) => {
    // gets are scoped
    const curr = get().list
    const next = curr.concat([item])

    // splits are scoped
    split({ list: next })

    // can call local actions
    split('reset')

    // can call global actions
    root.split('plus')
    root.split('minus')
    root.split('analytics.track')

    // and access global state
    root.get()
    root('analytics').get()
  },

  reset: (get, split, item, root) => {
    split({ val: '' })
  }
})
```

And another one

```js
const analytics = atom('analytics', { events: [] }, {
  track: (get, split, event) {
    split({ events: get().events.concat([event] )})
  }
})
```

It's possible to nest these infinitely - might be good or bad, but doesn't matter, it seems fairly elegant in general:

```js
const deep = analytics('deep', {})
deep.split({ value: 123 })
```

Observation only possible at the top, to emphasize this is still one tree and all:

```js
atom.observe(render)
```

All actions go through the global evolver. And it's actually possible to override the global evolver at runtime! This means, however, that you have to fully manually manage what happens with all the actions and how you namespace your state, etc.

```js
atom({}, customEvolve)
function customEvolve (get, split, action) {
  console.log('All actions are now intercepted', action)
}
```

Instead, it's also possible to only override evolve of the subatoms:

```js
atom('analytics')('deep', {}, evolve)
```

And once you've constructed your atoms, you can pass them around or provide/connect:

e.g. in the root
```js
<Provide atom={atom} />
```

e.g. in some subapp
```js
<Provide atom={atom('feedback')} />
<Connect>
  {(state, split) => <div>{state.text}</div>}
</Connect>
```

Seems pretty elegant overall! Lots of little hidden features, but the core usage is quite pragmatic and straightforward and it's the same atom we know (and love, right, right?)! Typical usage would probably be:

```js
const atom = createAtom({ merge, debug })

atom('onboarding', ...require('./actions/onboarding'))
atom('widget', ...require('./actions/widget'))
atom('feedback', ...require('./actions/feedback'))
atom('feeds', ...require('./actions/feeds'))
atom('entities', ...require('./actions/entities'))
atom('api', ...require('./actions/api'))

// and then pass this stuff around
atom('feedback').split('submit')
atom('feedback').get()

// or also
atom.split('feedback.submit')
atom.get().feedback
```

And a really cool thing is that these atoms and subatoms (mostly) conform to the atom interface. They preserve all of the original features and goals of the tiny-atom:

* it's open and flexible
* it's pragmatic
* it's tiny (?)
* works with all of the batteries - logger/devtools/merge/react/preact
* it doesn't assume anything about your state - you can use Immutable.js for example
* because it supports the top level stuff too it means you can drop it into any existing app

#### Tangent

The only thing that's removed here compared to #32 is splits as functions. String actions just keep proving to be simpler to implement and more powerful. It's still possible to bind all these splits as functions as demonstrated in #32, but you'd need to customize your evolver somehow.

Not sure how to elegantly incorporate it into the API and whether to do that at all. Feels like it would only make sense to use function actions if you completely remove splits as strings (?) to remove the duality. It's not cool that you can do both `atom.split.onboarding.start()` and `atom.split('onboarding.start')`.

---

The full implementation is here [examples/nested-example/atom-simpler.js](https://github.com/QubitProducts/tiny-atom/blob/d15f240ad95776d80b4533e967c2b6fed9a26218/examples/nested-example/atom-simpler.js).

### CODE REVIEW

**Comment by KidkArolis** [comment]
FYI, the state looks like this, each quark is in the top level with the namespace as the key:

image

This keeps the implementation really simple, avoids naming collisions (quark shadowing parent's state key) and makes things a ~bit simpler when using alternative state data structure (e.g. immutable).

**Comment by mhelvens** [comment]
Love it!

Except one thing: Why restrict `observe` to the top level? Isn't it more elegant if the whole tree was a fractal, i.e., self-similar on every level? You can never predict what ingenious use case someone might come up with, and placing artificial limits like this (like axios did) is almost never a good idea.

Or am I missing something?

**Comment by roberttod** [comment]
I like it. Nice that you no longer need to write an evolve function and you can attach actions directly. 

The one thing that bothers me is this function signature
```js
add: (get, split, item, root) =>
```
it's getting pretty long now, and it's strange that root comes after the payload. Could you return an actions creator function instead of an object?

**Global**
```js
atom({ b: 1 }, (atom) => {
  const { get, split } = atom
  return { minus: (payload) => { split({ b: get().b - 1 }) }
})
```

**Scoped**
```js
atom('todo', { b: 1 }, (atom) => {
  const { get, split, root } = atom
  return { minus: (payload) => { split({ b: get().b - 1 }) }
})
```

I also find the combination of global + scoped actions a little confusing... both seem useful separately but if a project ever used both together I think it would be easy to get lost.

Also, would like to see more info on `merge` and `debug`.

**Comment by KidkArolis** [comment]
I've spent a lot of time thinking about this. I've also tried incorporating this into some of our existing projects. My conclusion thus far is that both this #33 and  #32 are unnecessarily complicated. While scoped and fractal atoms seam neat, for a typical app it's awkward to work with local/global state by having to use `get/get.root` or `get/root.get` or anything like that. You take something simple, which is - here's your overall app state grouped by some concern, and here are some functions that operate over that and transition that state from one phase to the next. And you add more layers - oh, this one's locally scoped, so I need to call this like that, and to get global state I need to do that, but if I'm in a component, I need to do something different, because of how it's connected.

All in all, I'm inclined to close both of these PRs without merging them into the core `src` of the library. I'll probably keep them as examples in the examples dir for future reference. The original `tiny-atom` api with it's flexible `evolve` remains unbeaten in my book, because it allows you to adapt `tiny-atom` to exactly what your application needs without making many assumptions or introducing many global library concepts.

In fact, if we add "2 cores" or add "actions as strings and functions" or "gets/splits can be local and global" or "atoms can be global or scoped" to the core library, maybe that defeats a lot of the simplicity of `tiny-atom`. It'd be fine if those were truly "the best way" to do things, or had a lot of conceptual synergy and elegance. But from just trying to use them in a larger app, I immediately got put off. Maybe we'll come up with some better strategy in the future, but for now I think the experimentation should remain in each of the applications and good patterns can only emerge from writing a real app, not from messing with small examples.

So yeah - this point still stands: https://qubitproducts.github.io/tiny-atom/best-practises#extend.

Finally, some closing thoughts. If your app say really wants to separate concerns strongly between 2 subapps - say we have some `global` actions, `experiences` substate and `events` substate. You can do something as simple as this:

```js
module.exports = function createEvolve (actions) {
  const registry = { '': Object.assign({}, actions) }

  return { evolve, slice }

  function slice (namespace, actions) {
    registry[namespace] = actions
  }

  function evolve (get, split, action) {
    const namespace = action.type.split('.').slice(0, -1).join('.')
    if (namespace && registry[namespace]) {
      get = Object.assign(namespacedGet(get, namespace), { root: get })
      split = Object.assign(namespacedSplit(split, namespace), { root: split })
    }
    registry.actions[action.type](get, split, action.payload)
  }

  function namespacedGet (get, namespace) {
    return () => namespace.split('.').reduce((ref, segment) => ref[segment], get())
  }

  function namespacedSplit (split, namespace) {
    return (...args) => typeof args[0] === 'string'
      ? split(`${namespace}.${args[0]}`, ...args.slice(1))
      : split({ [namespace]: args[0] })
  }
}

```

The usage would be:

```js
const { evolve, slice } = createEvolve(actions.global)
slice('experiences', actions.experiences)
slice('events', actions.events)

const atom = createAtom(initialState, evolve)
```

Now, your `experiences` actions, for example, are scoped by default and state lives within a namespaced slice. And those actions can still access the global state and global actions via `get.root()` and `split.root(...)`. This might make sense for your app, but it won't make sense for all apps, so therefore is not enforced by the lib, but rather is an easy to write extension (that I'll write up  as a guide in docs).

**Comment by mhelvens** [comment]
Personally, I never cared about scoping at all. I'm just interested in decoupling. I want to do this:

```
// ----- feature1.js -----
import myAtom from 'myAtom'
myAtom(feature1State, feature1Actions)
// ----- feature2.js -----
import myAtom from 'myAtom'
myAtom(feature2State, feature2Actions)
```
instead of this:
```
// myAtom.js
import {feature1State, feature1Actions} from 'feature1'
import {feature2State, feature2Actions} from 'feature2'
myAtom({
  ...feature1State,
  ...feature2State
}, {
  ...feature1Actions,
  ...feature2Actions
})
```
But I'm fine with having everything be referenced from the root of the tree.

(And yes, I'm aware of the possibility of naming collisions, but that's rare and easy to solve.)

**Comment by KidkArolis** [comment]
Discussed in person with @mhelvens. I'm generally open to adding the "extend" state+actions feature. But the problem is that `tiny-atom` currently has no concept of actions. It's easy to write a wrapper that provides this functionality, but I'll keep this idea in mind for the future.

```js
module.exports = function createAtom (options) {
  const registry = {}
  const atom = createAtom({}, evolve, options)
  return Object.assign(atom, { fuse })

  function fuse ({ state, actions }) {
    Object.assign(registry, actions)
    atom.split(state)
  }

  function evolve (get, split, action) {
    registry.actions[action.type](get, split, action.payload)
  }
}
```

**Comment by KidkArolis** [comment]
Will merge via a new branch for history. Closing this one.

**Pull request closed without merging**
